### PR TITLE
Add posibility to provide dir for sounds and random sound selection

### PR DESCRIPTION
**Pull request by plafue**
Hello,

first of all thanks so much for all the work in rhasspy, it's really great!

I wanted to use this pull request to initiate a discussion about a possible feature: random sound selection for `recorded`, `error` and other sounds. Could make rhasspy a bit more fun by returning different sounds every time a voice command is handled.

I'm no python developer so this may look terrible.. feedback welcome.

### CODE REVIEW

**Comment by synesthesiam** [comment]
I like the idea! What about making it so that if you pass a directory instead a file, then a random WAV file is selected *each* time?

**Comment by plafue** [comment]
Hi @synesthesiam thanks for the reply! :wave: 

> What about making it so that if you pass a directory instead a file, then a random WAV file is selected each time?

I believe that the change in this PR does exactly that, it picks a random file within the provided directory. Which also means that sounds can be added/removed at anytime, but it also means that we read the contents of the directory _every time_.

I don't know what is expected in order to get this change merged (tests, documentation changes perhaps?). From a usability perspective the UI should at least mention that a directory is also a valid input for the form field.

**Comment by synesthesiam** [comment]
This is going to be in 2.5.10, so thank you! I made some slight modifications, so I'll close the PR rather than try to correct it after the merge.

I've made sure to credit you in the commits, though :slightly_smiling_face:

**Comment by plafue** [comment]
> This is going to be in 2.5.10, so thank you! I made some slight modifications, so I'll close the PR rather than try to correct it after the merge.
> 
> I've made sure to credit you in the commits, though slightly_smiling_face

Oh that's great news, thank you very much for letting me know! I'll share any other ideas I may have in the future...

Thanks for sharing your great work!

**Pull request closed without merging**
